<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ymir.Platform\Ymir.Platform.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Ymir.UnitTests" />
    <InternalsVisibleTo Include="Ymir.IntegrationTests" />
  </ItemGroup>
</Project>
