<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\Modules\VibeMaker\Ymir.VibeMaker.Infrastructure\Ymir.VibeMaker.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Ymir.UnitTests" />
    <InternalsVisibleTo Include="Ymir.IntegrationTests" />
  </ItemGroup>
</Project>
