// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ymir.VibeMaker.Infrastructure.Persistence;

#nullable disable

namespace Ymir.VibeMaker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VibeMakerDbContext))]
    partial class VibeMakerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("vibemaker")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ymir.VibeMaker.Domain.AgentExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AgentPrompt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("agent_prompt");

                    b.Property<Guid?>("AgentSessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("agent_session_id");

                    b.Property<Guid?>("AssistantMessageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assistant_message_id");

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("client_request_id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ended_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("ModelId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("model_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<Guid?>("RuntimeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("runtime_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<string>("ThinkingLevel")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("thinking_level");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<Guid>("UserMessageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_message_id");

                    b.HasKey("Id")
                        .HasName("pk_agent_executions");

                    b.HasIndex("ConversationId")
                        .IsUnique()
                        .HasDatabaseName("ux_agent_executions_active_per_conversation")
                        .HasFilter("[status] IN ('QUEUED', 'RUNNING')");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_agent_executions_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_agent_executions_status");

                    b.HasIndex("UserMessageId")
                        .HasDatabaseName("ix_agent_executions_user_message_id");

                    b.HasIndex("UserId", "ClientRequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_executions_user_id_client_request_id");

                    b.ToTable("agent_executions", "vibemaker");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.AgentRuntimeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("image_version");

                    b.Property<DateTimeOffset?>("LastActiveAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_active_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderRuntimeId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("provider_runtime_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_agent_runtimes");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_runtimes_user_id")
                        .HasFilter("[status] <> 'DELETED'");

                    b.ToTable("agent_runtimes", "vibemaker");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.AgentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderSessionId")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("provider_session_id");

                    b.Property<Guid?>("RuntimeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("runtime_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_agent_sessions");

                    b.HasIndex("ConversationId")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_sessions_conversation_id");

                    b.ToTable("agent_sessions", "vibemaker");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("ModelId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("model_id");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_conversations_project_id");

                    b.HasIndex("UserId", "ProjectId")
                        .HasDatabaseName("ix_conversations_user_id_project_id");

                    b.ToTable("conversations", "vibemaker");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.ExecutionArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("execution_id");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("modified_at");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("path");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.HasKey("Id")
                        .HasName("pk_execution_artifacts");

                    b.HasIndex("ExecutionId")
                        .HasDatabaseName("ix_execution_artifacts_execution_id");

                    b.ToTable("execution_artifacts", "vibemaker");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.ExecutionEventRecord", b =>
                {
                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("execution_id");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("data");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("event_type");

                    b.HasKey("ExecutionId", "Sequence")
                        .HasName("pk_execution_events");

                    b.ToTable("execution_events", "vibemaker");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("int")
                        .HasColumnName("chunk_count");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<int?>("Dimensions")
                        .HasColumnType("int")
                        .HasColumnName("dimensions");

                    b.Property<string>("EmbeddingModel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("embedding_model");

                    b.Property<string>("Error")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("error");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_documents");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_knowledge_documents_status");

                    b.HasIndex("ProjectId", "FileName")
                        .IsUnique()
                        .HasDatabaseName("ix_knowledge_documents_project_id_file_name")
                        .HasFilter("[status] = 'READY'");

                    b.HasIndex("ProjectId", "Status")
                        .HasDatabaseName("ix_knowledge_documents_project_id_status");

                    b.ToTable("knowledge_documents", "vibemaker");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.MakeTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("instructions");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_make_topics");

                    b.HasIndex("IsEnabled", "SortOrder")
                        .HasDatabaseName("ix_make_topics_is_enabled_sort_order");

                    b.ToTable("make_topics", "vibemaker");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.McpServerAccess", b =>
                {
                    b.Property<string>("ServerName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("server_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("enabled");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("mode");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserIdList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_id_list");

                    b.HasKey("ServerName")
                        .HasName("pk_mcp_server_access");

                    b.ToTable("mcp_server_access", "vibemaker");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ExecutionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("execution_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("message_type");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("role");

                    b.Property<long>("SequenceNo")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_no");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ConversationId", "SequenceNo")
                        .IsUnique()
                        .HasDatabaseName("ix_messages_conversation_id_sequence_no");

                    b.ToTable("messages", "vibemaker");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.MessageAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("file_name");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("message_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("path");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_message_attachments");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_message_attachments_message_id");

                    b.HasIndex("ConversationId", "MessageId")
                        .HasDatabaseName("ix_message_attachments_conversation_id_message_id");

                    b.ToTable("message_attachments", "vibemaker");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.OneDriveConnection", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("connected_at");

                    b.Property<string>("DriveId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("drive_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("last_error");

                    b.Property<string>("MicrosoftUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("microsoft_user_id");

                    b.Property<string>("ProtectedRefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("protected_refresh_token");

                    b.Property<string>("RootItemId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("root_item_id");

                    b.Property<string>("RootPath")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("root_path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserPrincipalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("user_principal_name");

                    b.HasKey("UserId")
                        .HasName("pk_onedrive_connections");

                    b.ToTable("onedrive_connections", "vibemaker");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.OneDriveSyncItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ETag")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("e_tag");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("item_id");

                    b.Property<DateTimeOffset?>("LocalModifiedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("local_modified_at");

                    b.Property<long?>("LocalSize")
                        .HasColumnType("bigint")
                        .HasColumnName("local_size");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("path");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("scope_id");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("synced_at");

                    b.HasKey("Id")
                        .HasName("pk_onedrive_sync_items");

                    b.HasIndex("ScopeId")
                        .HasDatabaseName("ix_onedrive_sync_items_scope_id");

                    b.ToTable("onedrive_sync_items", "vibemaker");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.OneDriveSyncScope", b =>
                {
                    b.Property<Guid>("ScopeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("scope_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("int")
                        .HasColumnName("attempts");

                    b.Property<int>("ConflictCount")
                        .HasColumnType("int")
                        .HasColumnName("conflict_count");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("conversation_id");

                    b.Property<string>("DriveId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("drive_id");

                    b.Property<string>("FolderItemId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("folder_item_id");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("folder_path");

                    b.Property<string>("LastError")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_synced_at");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("RootItemId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("root_item_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UploadPending")
                        .HasColumnType("bit")
                        .HasColumnName("upload_pending");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("ScopeId")
                        .HasName("pk_onedrive_sync_scopes");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_onedrive_sync_scopes_user_id");

                    b.HasIndex("UploadPending", "NextAttemptAt")
                        .HasDatabaseName("ix_onedrive_sync_scopes_upload_pending_next_attempt_at");

                    b.ToTable("onedrive_sync_scopes", "vibemaker");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<string>("SystemPrompt")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("system_prompt");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_projects_user_id");

                    b.ToTable("projects", "vibemaker");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AccessMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("access_mode");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("current_version_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("published_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("slug");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("source_path");

                    b.Property<bool>("SpaMode")
                        .HasColumnType("bit")
                        .HasColumnName("spa_mode");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sites");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_sites_slug");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sites_user_id");

                    b.ToTable("sites", "vibemaker");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.SiteShare", b =>
                {
                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("site_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.HasKey("SiteId", "UserId")
                        .HasName("pk_site_shares");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_site_shares_user_id");

                    b.ToTable("site_shares", "vibemaker");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.SiteTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("site_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_site_tickets");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_site_tickets_expires_at");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_site_tickets_site_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_site_tickets_token_hash");

                    b.ToTable("site_tickets", "vibemaker");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.SiteVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("error");

                    b.Property<int>("FileCount")
                        .HasColumnType("int")
                        .HasColumnName("file_count");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("site_id");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("source_path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("total_bytes");

                    b.HasKey("Id")
                        .HasName("pk_site_versions");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_site_versions_site_id");

                    b.ToTable("site_versions", "vibemaker");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.UserExtensionGrant", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("Capability")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("capability");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("effect");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("UserId", "Capability")
                        .HasName("pk_user_extension_grants");

                    b.ToTable("user_extension_grants", "vibemaker");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.UserSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("SystemPrompt")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("system_prompt");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_user_settings");

                    b.ToTable("user_settings", "vibemaker");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.AgentExecution", b =>
                {
                    b.HasOne("Ymir.VibeMaker.Domain.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agent_executions_conversations_conversation_id");

                    b.HasOne("Ymir.VibeMaker.Domain.Message", null)
                        .WithMany()
                        .HasForeignKey("UserMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agent_executions_messages_user_message_id");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.AgentSession", b =>
                {
                    b.HasOne("Ymir.VibeMaker.Domain.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agent_sessions_conversations_conversation_id");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.Conversation", b =>
                {
                    b.HasOne("Ymir.VibeMaker.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_conversations_projects_project_id");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.ExecutionArtifact", b =>
                {
                    b.HasOne("Ymir.VibeMaker.Domain.AgentExecution", null)
                        .WithMany()
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_execution_artifacts_agent_executions_execution_id");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.ExecutionEventRecord", b =>
                {
                    b.HasOne("Ymir.VibeMaker.Domain.AgentExecution", null)
                        .WithMany()
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_execution_events_agent_executions_execution_id");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.Message", b =>
                {
                    b.HasOne("Ymir.VibeMaker.Domain.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_conversations_conversation_id");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.MessageAttachment", b =>
                {
                    b.HasOne("Ymir.VibeMaker.Domain.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_message_attachments_conversations_conversation_id");

                    b.HasOne("Ymir.VibeMaker.Domain.Message", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_message_attachments_messages_message_id");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.OneDriveSyncItem", b =>
                {
                    b.HasOne("Ymir.VibeMaker.Domain.OneDriveSyncScope", null)
                        .WithMany()
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_onedrive_sync_items_onedrive_sync_scopes_scope_id");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.SiteShare", b =>
                {
                    b.HasOne("Ymir.VibeMaker.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_site_shares_sites_site_id");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.SiteTicket", b =>
                {
                    b.HasOne("Ymir.VibeMaker.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_site_tickets_sites_site_id");
                });

            modelBuilder.Entity("Ymir.VibeMaker.Domain.SiteVersion", b =>
                {
                    b.HasOne("Ymir.VibeMaker.Domain.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_site_versions_sites_site_id");
                });
#pragma warning restore 612, 618
        }
    }
}
