/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetMe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['Logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/providers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetLoginProviders'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/password-login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['PasswordLogin'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/me/password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['ChangePassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/dev/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['DevLogin'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/runtime': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetRuntime'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/models': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ListModels'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/conversations/{conversationId}/attachments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['UploadAttachment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/conversations/{conversationId}/messages': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ListMessages'];
    put?: never;
    post: operations['SendMessage'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/extensions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetMyExtensions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/conversations/{conversationId}/sites': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['PublishSite'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/make-topics': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ListMakeTopics'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ListProjects'];
    put?: never;
    post: operations['CreateProject'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetProject'];
    put?: never;
    post?: never;
    delete: operations['ArchiveProject'];
    options?: never;
    head?: never;
    patch: operations['UpdateProject'];
    trace?: never;
  };
  '/api/me/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetMySettings'];
    put: operations['UpdateMySettings'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/conversations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ListConversations'];
    put?: never;
    post: operations['CreateConversation'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/conversations/{conversationId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetConversation'];
    put?: never;
    post?: never;
    delete: operations['ArchiveConversation'];
    options?: never;
    head?: never;
    patch: operations['UpdateConversation'];
    trace?: never;
  };
  '/api/conversations/{conversationId}/files': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ListConversationFiles'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/conversations/{conversationId}/files/download': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['DownloadConversationFile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/conversations/{conversationId}/files/archive': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['DownloadConversationArchive'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/conversations/{conversationId}/artifacts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ListConversationArtifacts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/conversations/{conversationId}/artifacts/{executionId}/download': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['DownloadArtifact'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/conversations/{conversationId}/artifacts/{executionId}/archive': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['DownloadArtifactArchive'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/executions/{executionId}/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** SSE：execution 即時事件。支援 Last-Event-ID 斷線續傳。 */
    get: operations['StreamExecutionEvents'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/executions/{executionId}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['CancelExecution'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AdminListUsers'];
    put?: never;
    post: operations['AdminCreateLocalUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/users/{userId}/disable': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AdminDisableUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/users/{userId}/enable': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AdminEnableUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/users/{userId}/reset-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AdminResetPassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/overview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AdminGetOverview'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/runtimes/{userId}/stop': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AdminStopRuntime'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/audit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AdminSearchAudit'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AdminGetHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/settings/runtime': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AdminGetRuntimePolicy'];
    put: operations['AdminSaveRuntimePolicy'];
    post?: never;
    delete: operations['AdminResetRuntimePolicy'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/usage': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AdminGetUsage'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/settings/extensions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AdminGetExtensionPolicy'];
    put: operations['AdminSaveExtensionPolicy'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/users/{userId}/extensions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AdminGetUserExtensions'];
    put: operations['AdminSaveUserExtensions'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/mcp-servers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AdminListMcpServers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/mcp-servers/{name}/access': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['AdminSaveMcpServerAccess'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/knowledge': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetKnowledgeBase'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/knowledge/documents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['UploadKnowledgeDocument'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/knowledge/documents/{documentId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['RemoveKnowledgeDocument'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/knowledge/documents/{documentId}/retry': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['RetryKnowledgeDocument'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/knowledge/ask': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AskKnowledgeBase'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/sites': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ListSites'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/sites/{siteId}/publish': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['RepublishSite'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/sites/{siteId}/unpublish': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['UnpublishSite'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/sites/{siteId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['DeleteSite'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/connectors/onedrive': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetOneDriveStatus'];
    put?: never;
    post?: never;
    delete: operations['DisconnectOneDrive'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/connectors/onedrive/root': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['SetOneDriveRoot'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/conversations/{conversationId}/onedrive': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetConversationOneDriveStatus'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/conversations/{conversationId}/onedrive/sync': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['SyncConversationOneDrive'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/settings/oidc': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AdminGetOidcSettings'];
    put: operations['AdminSaveOidcSettings'];
    post?: never;
    delete: operations['AdminResetOidcSettings'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/settings/oidc/test': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AdminTestOidcSettings'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/settings/tunnel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AdminGetTunnelSettings'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/settings/tunnel/token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['AdminSetTunnelToken'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/settings/tunnel/hostname': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['AdminSetPublicHostname'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/make-topics': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AdminListMakeTopics'];
    put?: never;
    post: operations['AdminCreateMakeTopic'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/make-topics/{topicId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['AdminUpdateMakeTopic'];
    post?: never;
    delete: operations['AdminDeleteMakeTopic'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AdminMakeTopicResponse: {
      /** Format: uuid */
      id: string;
      name: string;
      description: null | string;
      instructions: string;
      /** Format: int32 */
      sortOrder: number | string;
      isEnabled: boolean;
      /** Format: date-time */
      updatedAt: string;
    };
    AdminOverviewResponse: {
      users: components['schemas']['UserCountsResponse'];
      executions: components['schemas']['ExecutionCountsResponse'];
      runtimes: components['schemas']['RuntimeSummaryResponse'][];
    };
    AdminUsageResponse: {
      /** Format: int32 */
      days: number | string;
      /** Format: int32 */
      dailyExecutionLimit: number | string;
      modelUsageAvailable: boolean;
      /** Format: double */
      monthlyBudgetUsd: number | string;
      users: components['schemas']['UserUsageResponse'][];
    };
    AdminUserResponse: {
      /** Format: uuid */
      id: string;
      displayName: string;
      accountName: null | string;
      email: null | string;
      role: components['schemas']['UserRole'];
      status: components['schemas']['UserStatus'];
      authMethod: components['schemas']['AuthMethod'];
      /** Format: date-time */
      lastLoginAt: null | string;
      /** Format: date-time */
      createdAt: string;
    };
    ArtifactGroupResponse: {
      /** Format: uuid */
      executionId: string;
      /** Format: uuid */
      conversationId: string;
      /** Format: uuid */
      messageId: null | string;
      /** Format: date-time */
      createdAt: string;
      files: components['schemas']['WorkspaceFileResponse'][];
    };
    AskKnowledgeRequest: {
      question: null | string;
      modelId: null | string;
    };
    AttachmentResponse: {
      /** Format: uuid */
      id: string;
      fileName: string;
      path: string;
      contentType: string;
      /** Format: int64 */
      size: number | string;
    };
    AuditLogItemResponse: {
      /** Format: int64 */
      id: number | string;
      /** Format: date-time */
      timestamp: string;
      action: string;
      result: components['schemas']['AuditResult'];
      /** Format: uuid */
      actorUserId: null | string;
      actorName: string;
      targetType: string;
      targetId: string;
      targetName: null | string;
      correlationId: null | string;
    };
    AuditLogPageResponse: {
      items: components['schemas']['AuditLogItemResponse'][];
      /** Format: int64 */
      nextBefore: null | number | string;
    };
    /** @enum {unknown} */
    AuditResult: 'Success' | 'Failure' | 'Denied';
    /** @enum {unknown} */
    AuthMethod: 'Oidc' | 'Local' | 'Dev';
    CancelExecutionResponse: {
      /** Format: uuid */
      executionId: string;
      status: string;
    };
    ChangePasswordRequest: {
      currentPassword: null | string;
      newPassword: null | string;
    };
    ConversationOneDriveResponse: {
      availability: components['schemas']['OneDriveAvailability'];
      rootPath: null | string;
      folderPath: null | string;
      state: null | components['schemas']['OneDriveSyncState'];
      /** Format: date-time */
      lastSyncedAt: null | string;
      /** Format: int32 */
      conflictCount: number | string;
      lastError: null | string;
    };
    ConversationResponse: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      projectId: null | string;
      title: string;
      modelId: null | string;
      status: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** Format: uuid */
      activeExecutionId?: null | string;
    };
    CreateConversationRequest: {
      /** Format: uuid */
      projectId: null | string;
      title: string;
    };
    CreateLocalUserRequest: {
      account: null | string;
      displayName: null | string;
      email: null | string;
      role: null | components['schemas']['UserRole'];
      initialPassword: null | string;
    };
    CreateProjectRequest: {
      name: string;
    };
    DailyExecutionResponse: {
      /** Format: date */
      date: string;
      /** Format: int32 */
      total: number | string;
      /** Format: int32 */
      failed: number | string;
    };
    DevLoginRequest: {
      account: null | string;
      displayName: null | string;
      role: null | components['schemas']['UserRole'];
    };
    ExecutionCountsResponse: {
      /** Format: int32 */
      running: number | string;
      /** Format: int32 */
      queued: number | string;
      /** Format: int32 */
      completedToday: number | string;
      /** Format: int32 */
      failedToday: number | string;
      /** Format: int32 */
      cancelledToday: number | string;
      trend: components['schemas']['DailyExecutionResponse'][];
    };
    /** @enum {unknown} */
    ExtensionGrantSetting: 'Inherit' | 'Allow' | 'Deny';
    ExtensionPolicyResponse: {
      defaults: components['schemas']['ExtensionValues'];
      restrictedNetwork: components['schemas']['RestrictedNetworkSupport'];
      /** Format: date-time */
      updatedAt: null | string;
      updatedByName: null | string;
    };
    ExtensionValues: {
      skills: boolean;
      mcp: boolean;
      internet: boolean;
      oneDrive: boolean;
    };
    KnowledgeAnswerResponse: {
      answer: null | string;
      insufficientData: boolean;
      modelAllowed: boolean;
      modelId: string;
      citations: components['schemas']['KnowledgeCitationResponse'][];
    };
    KnowledgeBaseResponse: {
      enabled: boolean;
      /** Format: int64 */
      maxFileBytes: number | string;
      /** Format: int32 */
      maxDocuments: number | string;
      supportedExtensions: string[];
      documents: components['schemas']['KnowledgeDocumentResponse'][];
    };
    KnowledgeCitationResponse: {
      /** Format: int32 */
      number: number | string;
      /** Format: uuid */
      documentId: string;
      fileName: string;
      /** Format: int32 */
      version: number | string;
      /** Format: int32 */
      ordinal: number | string;
      /** Format: int32 */
      page: null | number | string;
      excerpt: string;
      /** Format: double */
      score: number | string;
    };
    KnowledgeDocumentResponse: {
      /** Format: uuid */
      id: string;
      fileName: string;
      /** Format: int32 */
      version: number | string;
      /** Format: int64 */
      size: number | string;
      status: components['schemas']['KnowledgeDocumentStatus'];
      /** Format: int32 */
      chunkCount: number | string;
      error: null | string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    /** @enum {unknown} */
    KnowledgeDocumentStatus: 'Pending' | 'Indexing' | 'Ready' | 'Failed' | 'Removed';
    LoginProvidersResponse: {
      oidc: boolean;
      oidcDisplayName: null | string;
      password: boolean;
      devLogin: boolean;
    };
    MakeTopicResponse: {
      /** Format: uuid */
      id: string;
      name: string;
      description: null | string;
      /** Format: int32 */
      sortOrder: number | string;
    };
    /** @enum {unknown} */
    McpAccessMode: 'Everyone' | 'AdminsOnly' | 'SelectedUsers';
    McpServerAccessResponse: {
      name: string;
      description: string;
      enabled: boolean;
      mode: components['schemas']['McpAccessMode'];
      userIds: string[];
    };
    MeResponse: {
      /** Format: uuid */
      id: string;
      displayName: string;
      accountName: null | string;
      email: null | string;
      department: null | string;
      role: components['schemas']['UserRole'];
      status: components['schemas']['UserStatus'];
      authMethod: components['schemas']['AuthMethod'];
      mustChangePassword: boolean;
    };
    MessageResponse: {
      /** Format: uuid */
      id: string;
      role: string;
      messageType: string;
      content: string;
      /** Format: int64 */
      sequenceNo: number | string;
      /** Format: uuid */
      executionId: null | string;
      /** Format: date-time */
      createdAt: string;
      attachments: components['schemas']['AttachmentResponse'][];
    };
    ModelResponse: {
      id: string;
      displayName: string;
      isDefault: boolean;
      supportsImages: boolean;
      /** @default false */
      allowKnowledgeBase: boolean;
    };
    MyExtensionsResponse: {
      skillsAllowed: boolean;
      mcpAllowed: boolean;
      internetAllowed: boolean;
      oneDriveAllowed: boolean;
      inventoryAvailable: boolean;
      skills: string[];
      mcpServers: string[];
      platformMcpServers: components['schemas']['PlatformMcpServerSummary'][];
    };
    OidcSettingsResponse: {
      source: components['schemas']['OidcSettingsSource'];
      enabled: boolean;
      configured: boolean;
      tenantId: null | string;
      clientId: null | string;
      hasClientSecret: boolean;
      secretSource: components['schemas']['OidcSettingsSource'];
      /** Format: date-time */
      secretUpdatedAt: null | string;
      /** Format: date */
      secretExpiresOn: null | string;
      adminRole: string;
      displayName: string;
      redirectUri: string;
      /** Format: date-time */
      updatedAt: null | string;
      updatedByName: null | string;
    };
    /** @enum {unknown} */
    OidcSettingsSource: 'None' | 'Deployment' | 'Database';
    OidcTestResponse: {
      ok: boolean;
      message: string;
    };
    /** @enum {unknown} */
    OneDriveAvailability: 'NotAllowed' | 'NotConnected' | 'NeedsReauth' | 'NoRoot' | 'Ready';
    /** @enum {unknown} */
    OneDriveLinkState: 'NotConnected' | 'Connected' | 'NeedsReauth';
    OneDriveStatusResponse: {
      allowed: boolean;
      available: boolean;
      state: components['schemas']['OneDriveLinkState'];
      account: null | string;
      rootPath: null | string;
      /** Format: date-time */
      connectedAt: null | string;
      lastError: null | string;
    };
    /** @enum {unknown} */
    OneDriveSyncState: 'Synced' | 'Pending' | 'Failed' | null;
    PasswordLoginRequest: {
      account: null | string;
      password: null | string;
    };
    PlatformMcpServersResponse: {
      enabled: boolean;
      servers: components['schemas']['McpServerAccessResponse'][];
    };
    PlatformMcpServerSummary: {
      name: string;
      description: string;
    };
    ProjectResponse: {
      /** Format: uuid */
      id: string;
      name: string;
      systemPrompt: null | string;
      status: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    PublishSiteRequest: {
      name: null | string;
      sourcePath: null | string;
      /** @default false */
      spaMode: boolean;
    };
    RepublishSiteRequest: {
      /** Format: uuid */
      conversationId: null | string;
      sourcePath: null | string;
      spaMode: null | boolean;
    };
    ResetPasswordRequest: {
      newPassword: null | string;
    };
    /** @enum {unknown} */
    RestrictedNetworkSupport: 'Configured' | 'NotConfigured' | 'Unknown' | 'NotEnforced';
    RuntimePolicyResponse: {
      effective: components['schemas']['RuntimePolicyValues'];
      deployment: components['schemas']['RuntimePolicyValues'];
      source: components['schemas']['OidcSettingsSource'];
      /** Format: date-time */
      updatedAt: null | string;
      updatedByName: null | string;
    };
    RuntimePolicyValues: {
      /** Format: double */
      idleTimeoutMinutes: number | string;
      /** Format: double */
      executionTimeoutMinutes: number | string;
      /** Format: int32 */
      maxPendingExecutionsPerUser: number | string;
      /** Format: int32 */
      dailyExecutionLimit: number | string;
      /** Format: double */
      monthlyBudgetUsd: number | string;
    };
    /** @enum {unknown} */
    RuntimeStatus: 'NotCreated' | 'Created' | 'Running' | 'Busy' | 'Stopped' | 'Error' | 'Deleted';
    RuntimeStatusResponse: {
      status: string;
      provider: null | string;
      imageVersion: null | string;
      /** Format: date-time */
      lastActiveAt: null | string;
    };
    RuntimeSummaryResponse: {
      /** Format: uuid */
      userId: string;
      displayName: string;
      status: components['schemas']['RuntimeStatus'];
      /** Format: date-time */
      lastActiveAt: null | string;
    };
    SaveExtensionPolicyRequest: {
      skills: boolean;
      mcp: boolean;
      /** @default true */
      internet: boolean;
      /** @default false */
      oneDrive: boolean;
    };
    SaveMakeTopicRequest: {
      name: string;
      description: null | string;
      instructions: string;
      /** Format: int32 */
      sortOrder: number | string;
      isEnabled: boolean;
    };
    SaveMcpServerAccessRequest: {
      enabled: boolean;
      mode: components['schemas']['McpAccessMode'];
      userIds: null | string[];
    };
    SaveOidcSettingsRequest: {
      enabled: boolean;
      tenantId: null | string;
      clientId: null | string;
      clientSecret: null | string;
      /** Format: date */
      secretExpiresOn: null | string;
      adminRole: null | string;
      displayName: null | string;
    };
    SaveRuntimePolicyRequest: {
      /** Format: int32 */
      idleTimeoutMinutes: number | string;
      /** Format: int32 */
      executionTimeoutMinutes: number | string;
      /** Format: int32 */
      maxPendingExecutionsPerUser: number | string;
      /** Format: int32 */
      dailyExecutionLimit: number | string;
      /**
       * Format: double
       * @default 0
       */
      monthlyBudgetUsd: number | string;
    };
    SaveUserExtensionsRequest: {
      skills: components['schemas']['ExtensionGrantSetting'];
      mcp: components['schemas']['ExtensionGrantSetting'];
      internet?: components['schemas']['ExtensionGrantSetting'];
      oneDrive?: components['schemas']['ExtensionGrantSetting'];
    };
    SendMessageRequest: {
      content: string;
      /** Format: uuid */
      clientRequestId: string;
      modelId?: null | string;
      /** Format: uuid */
      makeTopicId?: null | string;
      attachmentIds?: null | string[];
    };
    SendMessageResponse: {
      /** Format: uuid */
      messageId: string;
      /** Format: uuid */
      executionId: string;
      eventStreamUrl: string;
    };
    ServiceHealthItem: {
      name: string;
      status: string;
      description: null | string;
      /** Format: int32 */
      durationMs: number | string;
    };
    ServiceHealthResponse: {
      status: string;
      checks: components['schemas']['ServiceHealthItem'][];
    };
    SetOneDriveRootRequest: {
      path: null | string;
    };
    SetPublicHostnameRequest: {
      hostname: null | string;
    };
    SetTunnelTokenRequest: {
      token: null | string;
    };
    /** @enum {unknown} */
    SiteAccessMode: 'Public' | 'AllUsers' | 'SelectedUsers';
    SiteResponse: {
      /** Format: uuid */
      id: string;
      name: string;
      /** Format: uri */
      url: null | string;
      status: components['schemas']['SiteStatus'];
      accessMode: components['schemas']['SiteAccessMode'];
      spaMode: boolean;
      /** Format: uuid */
      conversationId: string;
      sourcePath: string;
      /** Format: int32 */
      fileCount: number | string;
      /** Format: int64 */
      totalBytes: number | string;
      /** Format: date-time */
      publishedAt: null | string;
      /** Format: date-time */
      updatedAt: string;
    };
    SitesResponse: {
      enabled: boolean;
      /** Format: int32 */
      maxSites: number | string;
      sites: components['schemas']['SiteResponse'][];
    };
    /** @enum {unknown} */
    SiteStatus: 'Unpublished' | 'Published';
    /** Format: binary */
    Stream: string;
    TestOidcSettingsRequest: {
      tenantId: null | string;
    };
    TunnelSettingsResponse: {
      publicEdgeEnabled: boolean;
      hostname: null | string;
      hostnameSource: components['schemas']['OidcSettingsSource'];
      managementAvailable: boolean;
      configured: boolean;
      active: boolean;
      /** Format: date-time */
      tokenUpdatedAt: null | string;
      redirectUri: null | string;
    };
    UpdateConversationRequest: {
      title: null | string;
    };
    UpdateProjectRequest: {
      name: null | string;
      systemPrompt: null | string;
    };
    UpdateUserSettingsRequest: {
      systemPrompt: null | string;
    };
    UserCountsResponse: {
      /** Format: int32 */
      total: number | string;
      /** Format: int32 */
      active: number | string;
      /** Format: int32 */
      disabled: number | string;
      /** Format: int32 */
      admins: number | string;
      /** Format: int32 */
      recentlyActive: number | string;
    };
    UserExtensionsResponse: {
      skills: components['schemas']['ExtensionGrantSetting'];
      mcp: components['schemas']['ExtensionGrantSetting'];
      internet: components['schemas']['ExtensionGrantSetting'];
      oneDrive: components['schemas']['ExtensionGrantSetting'];
      effective: components['schemas']['ExtensionValues'];
    };
    /** @enum {unknown} */
    UserRole: 'User' | 'Admin';
    UserSettingsResponse: {
      systemPrompt: null | string;
    };
    /** @enum {unknown} */
    UserStatus: 'Active' | 'Disabled';
    UserUsageResponse: {
      /** Format: uuid */
      userId: string;
      displayName: string;
      /** Format: int32 */
      executions: number | string;
      /** Format: int32 */
      completed: number | string;
      /** Format: int32 */
      failed: number | string;
      /** Format: int32 */
      cancelled: number | string;
      /** Format: double */
      runMinutes: number | string;
      /** Format: int32 */
      last24Hours: number | string;
      /** Format: date-time */
      lastExecutionAt: null | string;
      runtimeStatus: null | components['schemas']['RuntimeStatus'];
      /** Format: double */
      spendUsd: null | number | string;
      /** Format: int64 */
      promptTokens: null | number | string;
      /** Format: int64 */
      completionTokens: null | number | string;
      /** Format: int64 */
      modelRequests: null | number | string;
      /** Format: double */
      budgetSpendUsd: null | number | string;
      /** Format: double */
      budgetUsd: null | number | string;
      /** Format: date-time */
      budgetResetAt: null | string;
    };
    WorkspaceFileResponse: {
      path: string;
      /** Format: int64 */
      size: number | string;
      /** Format: date-time */
      modifiedAt: string;
    };
    WorkspaceFilesResponse: {
      files: components['schemas']['WorkspaceFileResponse'][];
      truncated: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  GetMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MeResponse'];
        };
      };
    };
  };
  Logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  GetLoginProviders: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LoginProvidersResponse'];
        };
      };
    };
  };
  PasswordLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordLoginRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MeResponse'];
        };
      };
    };
  };
  ChangePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordRequest'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DevLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DevLoginRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MeResponse'];
        };
      };
    };
  };
  GetRuntime: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RuntimeStatusResponse'];
        };
      };
    };
  };
  ListModels: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ModelResponse'][];
        };
      };
    };
  };
  UploadAttachment: {
    parameters: {
      query?: {
        fileName?: string;
      };
      header?: never;
      path: {
        conversationId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/octet-stream': components['schemas']['Stream'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AttachmentResponse'];
        };
      };
    };
  };
  ListMessages: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MessageResponse'][];
        };
      };
    };
  };
  SendMessage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SendMessageRequest'];
      };
    };
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SendMessageResponse'];
        };
      };
    };
  };
  GetMyExtensions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MyExtensionsResponse'];
        };
      };
    };
  };
  PublishSite: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PublishSiteRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SiteResponse'];
        };
      };
    };
  };
  ListMakeTopics: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MakeTopicResponse'][];
        };
      };
    };
  };
  ListProjects: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectResponse'][];
        };
      };
    };
  };
  CreateProject: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateProjectRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectResponse'];
        };
      };
    };
  };
  GetProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectResponse'];
        };
      };
    };
  };
  ArchiveProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UpdateProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateProjectRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectResponse'];
        };
      };
    };
  };
  GetMySettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserSettingsResponse'];
        };
      };
    };
  };
  UpdateMySettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserSettingsRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserSettingsResponse'];
        };
      };
    };
  };
  ListConversations: {
    parameters: {
      query?: {
        projectId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConversationResponse'][];
        };
      };
    };
  };
  CreateConversation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateConversationRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConversationResponse'];
        };
      };
    };
  };
  GetConversation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConversationResponse'];
        };
      };
    };
  };
  ArchiveConversation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UpdateConversation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateConversationRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConversationResponse'];
        };
      };
    };
  };
  ListConversationFiles: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkspaceFilesResponse'];
        };
      };
    };
  };
  DownloadConversationFile: {
    parameters: {
      query?: {
        path?: string;
      };
      header?: never;
      path: {
        conversationId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DownloadConversationArchive: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ListConversationArtifacts: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ArtifactGroupResponse'][];
        };
      };
    };
  };
  DownloadArtifact: {
    parameters: {
      query?: {
        path?: string;
      };
      header?: never;
      path: {
        conversationId: string;
        executionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DownloadArtifactArchive: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: string;
        executionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  StreamExecutionEvents: {
    parameters: {
      query?: {
        lastEventId?: number | string;
      };
      header?: never;
      path: {
        executionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CancelExecution: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CancelExecutionResponse'];
        };
      };
    };
  };
  AdminListUsers: {
    parameters: {
      query?: {
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminUserResponse'][];
        };
      };
    };
  };
  AdminCreateLocalUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateLocalUserRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminUserResponse'];
        };
      };
    };
  };
  AdminDisableUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminUserResponse'];
        };
      };
    };
  };
  AdminEnableUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminUserResponse'];
        };
      };
    };
  };
  AdminResetPassword: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetPasswordRequest'];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminGetOverview: {
    parameters: {
      query?: {
        utcOffsetMinutes?: number | string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminOverviewResponse'];
        };
      };
    };
  };
  AdminStopRuntime: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminSearchAudit: {
    parameters: {
      query?: {
        action?: string;
        userId?: string;
        result?: components['schemas']['AuditResult'];
        from?: string;
        to?: string;
        before?: number | string;
        take?: number | string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuditLogPageResponse'];
        };
      };
    };
  };
  AdminGetHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ServiceHealthResponse'];
        };
      };
    };
  };
  AdminGetRuntimePolicy: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RuntimePolicyResponse'];
        };
      };
    };
  };
  AdminSaveRuntimePolicy: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SaveRuntimePolicyRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RuntimePolicyResponse'];
        };
      };
    };
  };
  AdminResetRuntimePolicy: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RuntimePolicyResponse'];
        };
      };
    };
  };
  AdminGetUsage: {
    parameters: {
      query?: {
        days?: number | string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminUsageResponse'];
        };
      };
    };
  };
  AdminGetExtensionPolicy: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExtensionPolicyResponse'];
        };
      };
    };
  };
  AdminSaveExtensionPolicy: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SaveExtensionPolicyRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExtensionPolicyResponse'];
        };
      };
    };
  };
  AdminGetUserExtensions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserExtensionsResponse'];
        };
      };
    };
  };
  AdminSaveUserExtensions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SaveUserExtensionsRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserExtensionsResponse'];
        };
      };
    };
  };
  AdminListMcpServers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PlatformMcpServersResponse'];
        };
      };
    };
  };
  AdminSaveMcpServerAccess: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SaveMcpServerAccessRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  GetKnowledgeBase: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['KnowledgeBaseResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UploadKnowledgeDocument: {
    parameters: {
      query?: {
        fileName?: string;
      };
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/octet-stream': components['schemas']['Stream'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['KnowledgeDocumentResponse'];
        };
      };
    };
  };
  RemoveKnowledgeDocument: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
        documentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RetryKnowledgeDocument: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
        documentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['KnowledgeDocumentResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AskKnowledgeBase: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AskKnowledgeRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['KnowledgeAnswerResponse'];
        };
      };
    };
  };
  ListSites: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SitesResponse'];
        };
      };
    };
  };
  RepublishSite: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        siteId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RepublishSiteRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SiteResponse'];
        };
      };
    };
  };
  UnpublishSite: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        siteId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SiteResponse'];
        };
      };
    };
  };
  DeleteSite: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        siteId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  GetOneDriveStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OneDriveStatusResponse'];
        };
      };
    };
  };
  DisconnectOneDrive: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OneDriveStatusResponse'];
        };
      };
    };
  };
  SetOneDriveRoot: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetOneDriveRootRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  GetConversationOneDriveStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConversationOneDriveResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  SyncConversationOneDrive: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AdminGetOidcSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OidcSettingsResponse'];
        };
      };
    };
  };
  AdminSaveOidcSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SaveOidcSettingsRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OidcSettingsResponse'];
        };
      };
    };
  };
  AdminResetOidcSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OidcSettingsResponse'];
        };
      };
    };
  };
  AdminTestOidcSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TestOidcSettingsRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OidcTestResponse'];
        };
      };
    };
  };
  AdminGetTunnelSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TunnelSettingsResponse'];
        };
      };
    };
  };
  AdminSetTunnelToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetTunnelTokenRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TunnelSettingsResponse'];
        };
      };
    };
  };
  AdminSetPublicHostname: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetPublicHostnameRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TunnelSettingsResponse'];
        };
      };
    };
  };
  AdminListMakeTopics: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminMakeTopicResponse'][];
        };
      };
    };
  };
  AdminCreateMakeTopic: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SaveMakeTopicRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminMakeTopicResponse'];
        };
      };
    };
  };
  AdminUpdateMakeTopic: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        topicId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SaveMakeTopicRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminMakeTopicResponse'];
        };
      };
    };
  };
  AdminDeleteMakeTopic: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        topicId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
