/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetMe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['Logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/dev/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['DevLogin'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/conversations/{conversationId}/messages': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ListMessages'];
    put?: never;
    post: operations['SendMessage'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ListWorkspaces'];
    put?: never;
    post: operations['CreateWorkspace'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetWorkspace'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/runtime': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetWorkspaceRuntime'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/conversations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ListConversations'];
    put?: never;
    post: operations['CreateConversation'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/conversations/{conversationId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetConversation'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/executions/{executionId}/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** SSE：execution 即時事件。支援 Last-Event-ID 斷線續傳。 */
    get: operations['StreamExecutionEvents'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/executions/{executionId}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['CancelExecution'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CancelExecutionResponse: {
      /** Format: uuid */
      executionId: string;
      status: string;
    };
    ConversationResponse: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      workspaceId: string;
      title: string;
      status: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CreateConversationRequest: {
      /** Format: uuid */
      workspaceId: string;
      title: string;
    };
    CreateWorkspaceRequest: {
      name: string;
    };
    DevLoginRequest: {
      account: null | string;
      displayName: null | string;
      role: null | components['schemas']['UserRole'];
    };
    MeResponse: {
      /** Format: uuid */
      id: string;
      displayName: string;
      accountName: null | string;
      email: null | string;
      department: null | string;
      role: components['schemas']['UserRole'];
      status: components['schemas']['UserStatus'];
    };
    MessageResponse: {
      /** Format: uuid */
      id: string;
      role: string;
      messageType: string;
      content: string;
      /** Format: int64 */
      sequenceNo: number | string;
      /** Format: uuid */
      executionId: null | string;
      /** Format: date-time */
      createdAt: string;
    };
    RuntimeStatusResponse: {
      /** Format: uuid */
      workspaceId: string;
      status: string;
      provider: null | string;
      imageVersion: null | string;
      /** Format: date-time */
      lastActiveAt: null | string;
    };
    SendMessageRequest: {
      content: string;
      /** Format: uuid */
      clientRequestId: string;
    };
    SendMessageResponse: {
      /** Format: uuid */
      messageId: string;
      /** Format: uuid */
      executionId: string;
      eventStreamUrl: string;
    };
    /** @enum {unknown} */
    UserRole: 'User' | 'Admin';
    /** @enum {unknown} */
    UserStatus: 'Active' | 'Disabled';
    WorkspaceResponse: {
      /** Format: uuid */
      id: string;
      name: string;
      status: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  GetMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MeResponse'];
        };
      };
    };
  };
  Logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DevLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DevLoginRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MeResponse'];
        };
      };
    };
  };
  ListMessages: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MessageResponse'][];
        };
      };
    };
  };
  SendMessage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SendMessageRequest'];
      };
    };
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SendMessageResponse'];
        };
      };
    };
  };
  ListWorkspaces: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkspaceResponse'][];
        };
      };
    };
  };
  CreateWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateWorkspaceRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkspaceResponse'];
        };
      };
    };
  };
  GetWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkspaceResponse'];
        };
      };
    };
  };
  GetWorkspaceRuntime: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RuntimeStatusResponse'];
        };
      };
    };
  };
  ListConversations: {
    parameters: {
      query?: {
        workspaceId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConversationResponse'][];
        };
      };
    };
  };
  CreateConversation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateConversationRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConversationResponse'];
        };
      };
    };
  };
  GetConversation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversationId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConversationResponse'];
        };
      };
    };
  };
  StreamExecutionEvents: {
    parameters: {
      query?: {
        lastEventId?: number | string;
      };
      header?: never;
      path: {
        executionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CancelExecution: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        executionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CancelExecutionResponse'];
        };
      };
    };
  };
}
